### ISSUE TITLE
Envio do questionario

### ISSUE THREAD

**Issue by artilheirocarol** [0101AlexandreLopes/Projeto-Integrador#3]
Boa noite pessoal. 
Sobre o envio de nosso questionario. Precisamos enviar para o maior numero de pessoas possiveis, via whatsapp, instagram, facebook e etc.
Eu enviei para grupos e muitos contatos via whatsapp e instagram.
Se cada um do grupo enviar com maior empenho possivel, teremos uma boa base de dados.
Como está sendo o envio de vocês?
Estão recebendo algum feedback?
Abs,

**Comment by artilheirocarol** [comment]
Vamos lutar por pelo menos 150 respostas? 👏👏👏👏
Somos 5, se cada um conseguir 30, chegaremos la 😊😊😊😊
![Screenshot_20230514-220907_Samsung Internet](https://github.com/0101AlexandreLopes/Projeto-Integrador/assets/132710979/4c205dcf-c97e-45b7-b0c2-628d9da9f169)

**Comment by 0101AlexandreLopes** [comment]
Legal Carol, vamos com tudo turma! @artilheirocarol ; @Alainsworth07 ; @anaclaradamasceno ;  @RenatoDaniel31

**Comment by Alainsworth07** [comment]
Já divulguei no meu whatsapp e pedi pra minha mãe divulgar, já que ela conhece e tem mais contatos do que eu. Vamos que vamos, time!

**Comment by RenatoDaniel31** [comment]
Bom dia pessoal
Pesquisa divulgado no meu WhatsApp

**Comment by artilheirocarol** [comment]
Estamos evoluindo pessoal!! 

👏👏

![Screenshot_20230515-110222_Samsung Internet](https://github.com/0101AlexandreLopes/Projeto-Integrador/assets/132710979/9cc0f419-31ea-4c00-9d90-6cbab23d957c)

**Comment by 0101AlexandreLopes** [comment]
Sugestões para perguntas Qualitativas:

1 - Quais motivações te levaram a baixar o APP? Você ainda percebe esses benefícios ao utilizar o Posto na hora de abastecer o seu veículo?

2 - Além de descontos e vantagens, há outro benefício que você gostaria de ver em um Programa de fidelidade? Numa escala de 0 a 10, quanto a ausência desse benefício te faz falta?

3 - Os descontos e as vantagens já utilizados por você, impactaram sua vida de alguma maneira? Se sim, como?

4 - Alguma vez você já encontrou erros no APP do Programa de Fidelidade que você participa? 

      4.1  Se sim, o suporte conseguiu te auxiliar como esperado?
      4.2  Conte-nos brevemente sobre sua experiência com o suporte técnico.

5 - Em termos tecnológicos, você definiria o APP como uma ferramenta difícil de utilizar ou intuitiva?

      5.1  Independente da definição que escolher, conte um elemento do APP que você não consegue mexer por não saber para o que serve e/ou por quando tentar acessar, você acha trabalhoso e demorado.

**Comment by anaclaradamasceno** [comment]
Boa noite, pessoal. Sobre a divulgação da pesquisa; estou divulgando nos meus grupos, postei no linkedin, mandei pros amigos e familiares e postei nos status do whatsapp.

**Comment by 0101AlexandreLopes** [comment]
Legal Ana, além de enviar também estou criando personas. 
Pois o nosso tempo é curto demais.

**Comment by artilheirocarol** [comment]
Bom dia pessoal.  Relacionado as perguntas qualitativas.
Tem total conexão com as nossas primeiras reuniões.  A maneira que nos empenhamos em estudar a IPIRANGA, os produtos oferecidos, a quantidade de apps disponiveis e chegamos ao ponto que achamos muito importante explorarmos. O programa de fidelizacao e vantagens, muito bem consolidado, KM DE VANTAGENS IPIRANGA. Devido alguns comentários bem negativos, vimos a importância de focarmos nesta questão. 
Sugestoes de perguntas:

1) Nos fale um pouco sobre sua visão, sobre ter pontos e premiacoes vinculadas ao seu consumo em serviços utilizados, principalmente relacionado ao consumo de abastecimento de combustível.

2) A dificuldade em resgatar uma premiação (pontos adquiridos) te decepciona? Isso influenciaria em uma decisão mais extrema, como abandonar o consumo da marca?

**Comment by artilheirocarol** [comment]
Sugestão da utilização das mesmas perguntas propostas pelo @0101AlexandreLopes , sem previsão nas respostas, respostas discursivas e livres.

https://forms.gle/91aSQDpCimDYj1ts9

**Comment by anaclaradamasceno** [comment]
Antes de fecharmos o formulário da pesquisa quantitativa, torci o tornozelo e até isso virou tática pra divulgação do questionário hahaha
![WhatsApp Image 2023-05-16 at 6 59 22 PM](https://github.com/0101AlexandreLopes/Projeto-Integrador/assets/100650361/701a02ce-a31c-47f6-a7ae-9d36fe931275)
![WhatsApp Image 2023-05-16 at 6 59 22 PM (1)](https://github.com/0101AlexandreLopes/Projeto-Integrador/assets/100650361/43193370-d5ba-4ee0-8720-b8db1153e397)
![WhatsApp Image 2023-05-16 at 6 59 23 PM](https://github.com/0101AlexandreLopes/Projeto-Integrador/assets/100650361/d5cbd745-3da7-4e11-963a-968e72f8f956)

**Comment by 0101AlexandreLopes** [comment]
Bom dia time!
Ontem finalizamos as coletas de dados da nossa pesquisa.
hoje vamos nos reunir para planejarmos a nossa apresentação!
Vamos com tudo. Para o Alto e Avante!
![giphy](https://github.com/0101AlexandreLopes/Projeto-Integrador/assets/132711465/f48f5be1-9032-477b-931f-9465e8433f21)

**Comment by 0101AlexandreLopes** [comment]
oi

**Comment by artilheirocarol** [comment]
Vai dar tudo certo!!

@anaclaradamasceno  Aninha, que bom que você está bem!! Logo, logo seu tornozelo estará 100%!

**Comment by anaclaradamasceno** [comment]
Obrigada @artilheirocarol <3333

Já estou trabalhando no nosso dashboard!!!

**Comment by Alainsworth07** [comment]
![IMG_2856](https://github.com/0101AlexandreLopes/Projeto-Integrador/assets/92619110/ec11d842-cc99-409c-92ca-7ddcf85efe44)
 
Eu fiz igual a Ana, divulguei no meu WhatsApp kkkkk
